# Generated by Django 3.2.8 on 2021-11-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_feedback_fm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeedback',
            options={'ordering': ['-up_votes']},
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='status',
            field=models.CharField(blank=True, choices=[('Suggestion', 'Suggestion'), ('Planned', 'Planned'), ('In-Progress', 'In-Progress'), ('Live', 'Live')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product_feedback_fm.comments'),
        ),
    ]
