# Generated by Django 3.2.8 on 2021-11-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_fm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ['id']},
        ),
    ]
