# Generated by Django 3.2.8 on 2021-11-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentuser',
            name='image',
            field=models.ImageField(blank=True, default='media/user_picture/bill-gates-profile-pic.jpg', null=True, upload_to='media/user_picture'),
        ),
    ]
